version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/node
permissions:
  - object: /home/ec2-user
    owner: ec2-user
    group: ec2-user
    type:
      - directory
      - file
hooks:
  BeforeInstall:
    - location: install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: post_install.sh
      timeout: 600
      runas: ec2-user
  ApplicationStart:
    - location: run.sh
      timeout: 120
      runas: ec2-user
  ApplicationStop:
    - location: stop.sh
      timeout: 120
      runas: ec2-user
  ValidateService:
    - location: validate.sh
      timeout: 60
      runas: ec2-user